<?php

namespace BCloud\SpoKuWaBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class SystemController__JMSInjector
{
    public static function inject($container) {
        $instance = new \BCloud\SpoKuWaBundle\Controller\SystemController();
        return $instance;
    }
}
