jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm:   sha1
            iterations: 1
            encode_as_base64: false
        BCloud\SpoKuWaBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_TEACHER:     ROLE_STUDENT
        ROLE_CLIENT:      [ROLE_TEACHER, ROLE_STUDENT]
        ROLE_ADMIN: [ROLE_STUDENT, ROLE_TEACHER, ROLE_CLIENT, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
            chain:
                providers: [in_memory, user_db]
        in_memory:
            memory:
                users:
                    admin:  { password: d033e22ae348aeb5660fc2140aec35850c4da997, roles: ['ROLE_ADMIN'] }
        user_db:
            entity: { class: BCloud\SpoKuWaBundle\Entity\User, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false

        spokuwa:
            pattern:    ^/spokuwa
            provider: user_db
            form_login:
                check_path: /spokuwa/login_check
                login_path: login
            logout:
                path:   /logout
                target: /
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

        admin:
            pattern:    ^/admin
            provider: in_memory
            http_basic:
                realm: "Admin-Area"

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/homepage, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: http }
        - { path: ^/admin, roles: ROLE_ADMIN, requires_channel: https }
        - { path: ^/spokuwa, roles: ROLE_STUDENT}
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
