parameters:
#    b_cloud_spo_ku_wa.example.class: BCloud\SpoKuWaBundle\Example

services:
#    b_cloud_spo_ku_wa.example:
#        class: %b_cloud_spo_ku_wa.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
