<?php

namespace Proxies\__CG__\BCloud\SpoKuWaBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Coursedata extends \BCloud\SpoKuWaBundle\Entity\Coursedata implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setTeacher($teacher)
    {
        $this->__load();
        return parent::setTeacher($teacher);
    }

    public function getTeacher()
    {
        $this->__load();
        return parent::getTeacher();
    }

    public function setDescription($description)
    {
        $this->__load();
        return parent::setDescription($description);
    }

    public function getDescription()
    {
        $this->__load();
        return parent::getDescription();
    }

    public function setLessonStart($lessonStart)
    {
        $this->__load();
        return parent::setLessonStart($lessonStart);
    }

    public function getLessonStart()
    {
        $this->__load();
        return parent::getLessonStart();
    }

    public function setLessonEnd($lessonEnd)
    {
        $this->__load();
        return parent::setLessonEnd($lessonEnd);
    }

    public function getLessonEnd()
    {
        $this->__load();
        return parent::getLessonEnd();
    }

    public function setMemberMax($memberMax)
    {
        $this->__load();
        return parent::setMemberMax($memberMax);
    }

    public function getMemberMax()
    {
        $this->__load();
        return parent::getMemberMax();
    }

    public function setMemberMin($memberMin)
    {
        $this->__load();
        return parent::setMemberMin($memberMin);
    }

    public function getMemberMin()
    {
        $this->__load();
        return parent::getMemberMin();
    }

    public function setSelectable($selectable)
    {
        $this->__load();
        return parent::setSelectable($selectable);
    }

    public function getSelectable()
    {
        $this->__load();
        return parent::getSelectable();
    }

    public function setSemester($semester)
    {
        $this->__load();
        return parent::setSemester($semester);
    }

    public function getSemester()
    {
        $this->__load();
        return parent::getSemester();
    }

    public function setTerm($term)
    {
        $this->__load();
        return parent::setTerm($term);
    }

    public function getTerm()
    {
        $this->__load();
        return parent::getTerm();
    }

    public function setCourse(\BCloud\SpoKuWaBundle\Entity\Course $course = NULL)
    {
        $this->__load();
        return parent::setCourse($course);
    }

    public function getCourse()
    {
        $this->__load();
        return parent::getCourse();
    }

    public function addMember(\BCloud\SpoKuWaBundle\Entity\Student $members)
    {
        $this->__load();
        return parent::addMember($members);
    }

    public function removeMember(\BCloud\SpoKuWaBundle\Entity\Student $members)
    {
        $this->__load();
        return parent::removeMember($members);
    }

    public function getMembers()
    {
        $this->__load();
        return parent::getMembers();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'teacher', 'description', 'lessonStart', 'lessonEnd', 'memberMax', 'memberMin', 'selectable', 'semester', 'term', 'course', 'members');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}