Course:
    type: entity
    table: course
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 200
            fixed: false
            nullable: false
        scope:
            type: boolean
            nullable: false
    manyToOne:
        system:
            targetEntity: System
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                system_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
