Member:
    type: entity
    table: member
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
    manyToOne:
        coursedata:
            targetEntity: Coursedata
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                coursedata_id:
                    referencedColumnName: id
            orphanRemoval: false
        student:
            targetEntity: Student
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                student_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
