School:
    type: entity
    table: school
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        province:
            type: smallint
            nullable: false
        name:
            type: string
            length: 255
            fixed: false
            nullable: false
        type:
            type: string
            length: 255
            fixed: false
            nullable: true
        street:
            type: string
            length: 255
            fixed: false
            nullable: true
        zip:
            type: integer
            unsigned: false
            nullable: true
        city:
            type: string
            length: 255
            fixed: false
            nullable: true
    lifecycleCallbacks: {  }
