User:
    type: entity
    table: user
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        username:
            type: string
            length: 255
            fixed: false
            nullable: false
        password:
            type: string
            length: 255
            fixed: false
            nullable: false
        salt:
            type: string
            length: 255
            fixed: false
            nullable: false
        email:
            type: string
            length: 255
            fixed: false
            nullable: true
        type:
            type: integer
            nullable: false
        isActive:
            type: boolean
            nullable: false
            column: is_active
        registered:
            type: datetime
            nullable: false
    lifecycleCallbacks: {  }
